# Generated by Django 4.2.4 on 2023-08-13 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager_app', '0002_codewavejob_score_hackernewsjob_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codewavepolloption',
            name='parent',
        ),
        migrations.AddField(
            model_name='codewavecomment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codewavepolloption',
            name='poll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codewavepolloption',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hackernewscomment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavecomment',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='codewavejob',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavejob',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='codewavepoll',
            name='descendants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavepoll',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavepoll',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='codewavepolloption',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavepolloption',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='codewavestory',
            name='descendants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavestory',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codewavestory',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewscomment',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsjob',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackernewsjob',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewspoll',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackernewspoll',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewspolloption',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackernewspolloption',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackernewsstory',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hackernewsstory',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
